id: P007040
initial_creation_type: ocr
source_metadata:
  id: bdr:W22116
  title: གསུང་འབུམ། ངག་དབང་བསྟན་འཛིན་འཕྲིན་ལས
  author: ''
  volumes:
    5124e87e362c43648503bf81f25fefc0:
      image_group_id: I00KG010102
      title: ''
      volume_number: 1
      total_pages: 1060
ebook_metadata:
  title: གསུང་འབུམ། ངག་དབང་བསྟན་འཛིན་འཕྲིན་ལས
  author: ''
  sku: P007040
  cover: cover.jpg
  layers:
  - pagination
