id: opecha:P007040
initial_creation_type: ocr
source_metadata:
  id: bdr:W22116
  title: གསུང་འབུམ། ངག་དབང་བསྟན་འཛིན་འཕྲིན་ལས
  volume:
    8aa5fcd1155d47baae366736df809a58:
      image_group_id: I00KG010102
      title: Volume 1 of gsung 'bum/_ngag dbang bstan 'dzin 'phrin las
      volume_number: 1
      total_pages: 1060
  author: ''
ebook_metadata:
  title: གསུང་འབུམ། ངག་དབང་བསྟན་འཛིན་འཕྲིན་ལས
  author: ''
  sku: P007040
  cover: cover.jpg
  layers:
  - pagination
