id: IDFE285F0
legacy_id: P007040
ocr_import_info:
  bdrc_scan_id: W22116
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T03:17:12'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:42:35.450971+00:00'
last_modified: 2022-09-02 04:43:17.632441
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22116
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22116
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ངག་དབང་བསྟན་འཛིན་འཕྲིན་ལས།
  author: སྐྱིད་ཤོད་ཞབས་དྲུང་ངག་དབང་བསྟན་འཛིན་འཕྲིན་ལས།
statistics:
  ocr_word_mean_confidence_index: 0.6238082176967075
  ocr_word_median_confidence_index: 0.6600000262260437
quality: null
bases:
  I00KG010102:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG010102
      total_pages: 1060
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG010102.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6238082176967075
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
