id: IDFE285F0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T03:23:46+00:00'
last_modified: '2022-06-08T16:11:02.422369+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22116
  title: གསུང་འབུམ། ངག་དབང་བསྟན་འཛིན་འཕྲིན་ལས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DE8E:
      image_group_id: I00KG010102
      title: Volume 1 of gsung 'bum/_ngag dbang bstan 'dzin 'phrin las
      total_pages: 1060
      order: 1
      base_file: DE8E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
